name: build
on:
  workflow_dispatch:
jobs:
  ayugram-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5.0.0

      - name: Cache dependencies
        uses: actions/cache@v4.3.0
        with:
          path: |
            ~/.cache
            td-*/build
            build
          key: ${{ runner.os }}-ayugram-desktop-${{ hashFiles('**/PKGBUILD', '**/*.patch') }}
          restore-keys: |
            ${{ runner.os }}-ayugram-desktop-

      - name: build
        uses: heyhusen/archlinux-package-action@v2.4.0
        with:
          path: ayugram-desktop
          flags: '-s --noconfirm'
          aur: true

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          path: ./*/*.pkg.tar.zst
          name: ayugram-desktop

  ayugram-desktop-git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5.0.0

      - name: Cache dependencies
        uses: actions/cache@v4.3.0
        with:
          path: |
            ~/.cache
            build_tde2e
            build
            deps
          key: ${{ runner.os }}-ayugram-desktop-git-${{ hashFiles('**/PKGBUILD', '**/*.patch') }}-${{ hashFiles('**/.gitmodules') }}
          restore-keys: |
            ${{ runner.os }}-ayugram-desktop-git-

      - name: build
        uses: heyhusen/archlinux-package-action@v2.4.0
        with:
          path: ayugram-desktop-git
          flags: '-s --noconfirm'
          aur: true

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          path: ./*/*.pkg.tar.zst
          name: ayugram-desktop-git
